name: rtb_driver
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  google_maps_flutter: ^1.2.0
  location: 3.1.0
  app_settings: 4.0.1+1
  maps_launcher: ^2.0.0

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/img_splash_logo.png
    - assets/img_ride_the_bee.png
    - assets/ic_eye_open.png
    - assets/home_background.png
    - assets/ic_menus.png
    - assets/ic_notification.png
    - assets/img_profile_example.png
    - assets/img_example_profile.png
    - assets/ic_trips.png
    - assets/ic_speed.png
    - assets/ic_clock.png
    - assets/ic_track.png
    - assets/img_notif_example.png
    - assets/ic_three_dots.png
    - assets/ic_close_black.png
    - assets/ic_circle_right.png
    - assets/ic_star.png
    - assets/ic_graycircle_arrow.png
    - assets/ic_yellow_home.png
    - assets/ic_yellow_trips.png
    - assets/ic_yellow_chat.png
    - assets/ic_yellow_reviews.png
    - assets/ic_back_yellow.png
    - assets/ic_notification.png
    - assets/img_message.png
    - assets/ic_yellow_dropdown.png
    - assets/ic_search_white.png
    - assets/ic_minibus.png
    - assets/img_ridethebee.png
    - assets/ic_black_circle.png
    - assets/ic_yellow_circle.png
    - assets/ic_dots.png
    - assets/ic_yellow_right.png
    - assets/ic_black_uparrow.png
    - assets/ic_black_circle.png
    - assets/ic_yellow_from.png
    - assets/ic_yellow_location.png
    - assets/ic_current_location.png
    - assets/ic_km.png
    - assets/ic_yellow_message.png
    - assets/ic_yellow_arrow_right.png
    - assets/img_thankyou.png
    - assets/img_available_seat.png
    - assets/img_booked_seat.png
    - assets/img_selected_seat.png
    - assets/ic_new_back_yellow.png
    - assets/img_seat_background.png
    - assets/img_driver_home.png
    - assets/ic_end_dot.png
    - assets/img_menu_background.png
    - assets/ic_black_dropdown.png
    - assets/img_alert.png
    - assets/img_share.png
    - assets/img_emergency.png
    - assets/img_home_edit.png
    - assets/ic_back_black.png
    - assets/ic_send.png
    - assets/ic_track_yellow.png
    - assets/ic_search_yellow.png
    - assets/ic_yellow_back.png

  fonts:
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/poppins_bold.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/poppins_medium.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
